package com.sqldalmaker.todolist.model.dto;

// Code generated by a tool. DO NOT EDIT.
// https://sqldalmaker.sourceforge.net/

public class Group  {

    private Integer gId;  // q
    private String gName;  // q
    private Integer tasksCount;  // q

    public Integer getGId() {
        return this.gId;
    }

    public void setGId(Integer gId) {
        this.gId = gId;
    }

    public String getGName() {
        return this.gName;
    }

    public void setGName(String gName) {
        this.gName = gName;
    }

    public Integer getTasksCount() {
        return this.tasksCount;
    }

    public void setTasksCount(Integer tasksCount) {
        this.tasksCount = tasksCount;
    }
}