package com.sqldalmaker.todolist.model.dto;

// Code generated by a tool. DO NOT EDIT.
// https://sqldalmaker.sourceforge.net/

public class Group  {

    private Integer gID;  // t
    private String gName;  // t
    private Integer gTasksCount;  // xml(g_tasks_count)

    public Integer getGID() {
        return this.gID;
    }

    public void setGID(Integer gID) {
        this.gID = gID;
    }

    public String getGName() {
        return this.gName;
    }

    public void setGName(String gName) {
        this.gName = gName;
    }

    public Integer getGTasksCount() {
        return this.gTasksCount;
    }

    public void setGTasksCount(Integer gTasksCount) {
        this.gTasksCount = gTasksCount;
    }
}