package com.sqldalmaker.todolist.model.dto;

// Code generated by a tool. DO NOT EDIT.
// https://sqldalmaker.sourceforge.net/

public class Group  {

    private java.lang.Integer gId;  // t
    private java.lang.String gName;  // t
    private Integer gTasksCount;  // xml(g_tasks_count)

    public java.lang.Integer getGId() {
        return this.gId;
    }

    public void setGId(java.lang.Integer gId) {
        this.gId = gId;
    }

    public java.lang.String getGName() {
        return this.gName;
    }

    public void setGName(java.lang.String gName) {
        this.gName = gName;
    }

    public Integer getGTasksCount() {
        return this.gTasksCount;
    }

    public void setGTasksCount(Integer gTasksCount) {
        this.gTasksCount = gTasksCount;
    }
}