package com.sqldalmaker.todolist.model.dto;

// Code generated by a tool. DO NOT EDIT.
// https://sqldalmaker.sourceforge.net/

public class Task  {

    private Integer tId;  // t
    private Integer gId;  // t
    private Integer tPriority;  // t
    private String tDate;  // t
    private String tSubject;  // t
    private String tComments;  // t

    public Integer getTId() {
        return this.tId;
    }

    public void setTId(Integer tId) {
        this.tId = tId;
    }

    public Integer getGId() {
        return this.gId;
    }

    public void setGId(Integer gId) {
        this.gId = gId;
    }

    public Integer getTPriority() {
        return this.tPriority;
    }

    public void setTPriority(Integer tPriority) {
        this.tPriority = tPriority;
    }

    public String getTDate() {
        return this.tDate;
    }

    public void setTDate(String tDate) {
        this.tDate = tDate;
    }

    public String getTSubject() {
        return this.tSubject;
    }

    public void setTSubject(String tSubject) {
        this.tSubject = tSubject;
    }

    public String getTComments() {
        return this.tComments;
    }

    public void setTComments(String tComments) {
        this.tComments = tComments;
    }
}