package com.sqldalmaker.todolist.model.dto;

// Code generated by a tool. DO NOT EDIT.
// https://sqldalmaker.sourceforge.net/

public class Task  {

    private Integer tID;  // t
    private Integer gID;  // t
    private Integer tPriority;  // t
    private String tDate;  // t
    private String tSubject;  // t
    private String tComments;  // t

    public Integer getTID() {
        return this.tID;
    }

    public void setTID(Integer tID) {
        this.tID = tID;
    }

    public Integer getGID() {
        return this.gID;
    }

    public void setGID(Integer gID) {
        this.gID = gID;
    }

    public Integer getTPriority() {
        return this.tPriority;
    }

    public void setTPriority(Integer tPriority) {
        this.tPriority = tPriority;
    }

    public String getTDate() {
        return this.tDate;
    }

    public void setTDate(String tDate) {
        this.tDate = tDate;
    }

    public String getTSubject() {
        return this.tSubject;
    }

    public void setTSubject(String tSubject) {
        this.tSubject = tSubject;
    }

    public String getTComments() {
        return this.tComments;
    }

    public void setTComments(String tComments) {
        this.tComments = tComments;
    }
}