package com.sqldalmaker.todolist.model.dto;

// Code generated by a tool. DO NOT EDIT.
// https://sqldalmaker.sourceforge.net/

public class Task  {

    private java.lang.Integer tId;  // t
    private java.lang.Integer gId;  // t
    private java.lang.Integer tPriority;  // t
    private java.lang.String tDate;  // t
    private java.lang.String tSubject;  // t
    private java.lang.String tComments;  // t

    public java.lang.Integer getTId() {
        return this.tId;
    }

    public void setTId(java.lang.Integer tId) {
        this.tId = tId;
    }

    public java.lang.Integer getGId() {
        return this.gId;
    }

    public void setGId(java.lang.Integer gId) {
        this.gId = gId;
    }

    public java.lang.Integer getTPriority() {
        return this.tPriority;
    }

    public void setTPriority(java.lang.Integer tPriority) {
        this.tPriority = tPriority;
    }

    public java.lang.String getTDate() {
        return this.tDate;
    }

    public void setTDate(java.lang.String tDate) {
        this.tDate = tDate;
    }

    public java.lang.String getTSubject() {
        return this.tSubject;
    }

    public void setTSubject(java.lang.String tSubject) {
        this.tSubject = tSubject;
    }

    public java.lang.String getTComments() {
        return this.tComments;
    }

    public void setTComments(java.lang.String tComments) {
        this.tComments = tComments;
    }
}